Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"

  config.vm.network "public_network"
  
  config.vm.define "sfpractice"
  
  config.vm.provision "file", source: "D:\EmptyFile", destination: "EmptyFile"
  
  config.vm.provider "virtualbox" do |v|
     v.name = "sfpractice"
	 v.memory = 4096
     v.cpus = 2
  end
  
  config.vm.hostname = "sfpractice"
  
  config.vm.provision "shell", inline: <<-SHELL
	apt update
	apt install -y python3- python3-pip 
	apt update
	apt install libpq-dev python-dev
	pip install psycopg2
	pip install django
  SHELL

end